name: todo_info
description: The TODO Info library analyzes code for TODO comments and reports.
version: 1.0.0
repository: https://github.com/JhonaCodes/todo_info
homepage: https://jhonacode.com

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  glob: ^2.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
